load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')

platform :ios, '13.0'

# CocoaPods analytics sends network stats. If you want to disable this, uncomment the following line.
# disable_cocoapods_analytics!

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        
        ## dart: [PermissionGroup.camera]
        'PERMISSION_CAMERA=1',
        
        ## dart: [PermissionGroup.photos]
        'PERMISSION_PHOTOS=1',
        
        ## dart: [PermissionGroup.microphone]
        'PERMISSION_MICROPHONE=1',
        
        ## dart: [PermissionGroup.notification]
        'PERMISSION_NOTIFICATIONS=1',
      ]
    end
  end
end
